/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TEA */

#ifndef _Included_TEA
#define _Included_TEA
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TEA
 * Method:    encrypt
 * Signature: ([B[J)V
 */
JNIEXPORT void JNICALL Java_TEA_encrypt
  (JNIEnv *, jclass, jbyteArray, jlongArray);

/*
 * Class:     TEA
 * Method:    decrypt
 * Signature: ([B[J)V
 */
JNIEXPORT void JNICALL Java_TEA_decrypt
  (JNIEnv *, jclass, jbyteArray, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
